#!/bin/bash

if xrandr --query | grep -q "HDMI-1 connected"; then
    echo "HDMI-1 connected"
    xrandr --output eDP-1 --off --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output DP-2 --off
fi

