preload = ~/.config/hypr/wallpapers/night_city.png

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off
wallpaper = ,~/.config/hypr/wallpapers/night_city.png

ipc = off
