general {
    lock_cmd = pidof hyprlock || hyprlock             # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session          # lock before suspend.
    after_sleep_cmd = ~/.config/hypr/scripts/hypr-dpms on  # turn displays back on after suspend.
}

listener {
    timeout = 300                                    # 5min
    on-timeout = loginctl lock-session              # lock screen.
}

listener {
    timeout = 330                                    # 5.5min
    on-timeout = ~/.config/hypr/scripts/hypr-dpms off # turn displays off.
    on-resume = ~/.config/hypr/scripts/hypr-dpms on   # turn displays back on.
}

listener {
    timeout = 1800                                   # 30min
    on-timeout = systemctl suspend                   # suspend pc.
}
