preload = ~/.config/hypr/wallpapers/wallpaper_street.png

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off
wallpaper = eDP-1,~/.config/hypr/wallpapers/wallpaper_street.png
wallpaper = HDMI-A-1,~/.config/hypr/wallpapers/wallpaper_street.png
