preload = ~/.config/hypr/wallpapers/wallpaper_street.png

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off
wallpaper = ,~/.config/hypr/wallpapers/wallpaper_street.png

ipc = off
