#!/bin/bash
sleep 1
hyprctl keyword monitor eDP-1, 3072x1920, 0x0,2, vrr, 1
# Get the output and count the number of lines matching the regex
line_count=$(hyprctl monitors | grep -P 'Monitor\s(?!eDP-1).+?\s\(ID\s\d+\):' | wc -l)

# Check if the line count is more than 1
if [ "$line_count" -gt 0 ]; then
    # disable the internal monitor on lid close
    hyprctl keyword monitor HDMI-A-1,1920x1080@100,auto,1
fi
